### ISSUE TITLE
Prisoners can't use brig's vendors

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1825]
### Testmerges

-

### Description of the bug

The brig common area has a number of vendors, but one problem is that those vendors require an ID to be able to pay for them, which the prisoners don't have. One solution would be to give them an ATM to withdraw money vie their account number and PIN (that nobody would remember, so probably would need to find it somehow via a verb), or set those vendors to be free.

### What's the difference with what should have happened?

Things in the brig common area should be usable by prisoners.

### How do we reproduce this bug?

1. Get put in brig as per protocol without ID
2. Try to get some smokes - you can't

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
you can check your memory for the PIN number in IC tab and the notes verb? worked for me.
Just need to add the ATM i guess.
Add the mapping label.

**Comment by Huffie56** [comment]
@ThePiachu so i looked around how to fix the issue and what i found is that you can't access ATM without the card on you.
So the easy fix is to add an ATM inside the processing area in brig and let the MP withdraw the cash...
i will do the fix

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/1904
PR to fix it

**Comment by Huffie56** [comment]
i did a fix a while back by adding an ATM in brig should fix the issue??

**Comment by ThePiachu** [comment]
You mean the ATM that is outside of the area prisoners will be staying at?
![image](https://user-images.githubusercontent.com/964559/211467866-010bc8e0-c4ae-4fba-b177-ce90888a5b1a.png)

That doesn't really fix the issue since I doubt an MP will let a prisoner out to do a withdrawal...

**Comment by Huffie56** [comment]
> You mean the ATM that is outside of the area prisoners will be staying at? ![image](https://user-images.githubusercontent.com/964559/211467866-010bc8e0-c4ae-4fba-b177-ce90888a5b1a.png)
> 
> That doesn't really fix the issue since I doubt an MP will let a prisoner out to do a withdrawal...

that's the best solution i could come up with as a mapper since prisoners can't have ID inside the brig.....
and you can't withdraw money without your ID sadly....

**Comment by ThePiachu** [comment]
Can't you log in with your account number and pin? I guess if you can't, then the vendors should be just free in the brig...

**Comment by Huffie56** [comment]
> Can't you log in with your account number and pin? I guess if you can't, then the vendors should be just free in the brig...

the idea is to ask MP to withdraw cash for prisoner to use ....
other than that you can make vendor free.. but that would be rewarding them from doing breaking law....
